#spring:
#  application:
#    name: coupon-eureka
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    #标识是否从Eureka Server 获取注册写信息，默认是 true，如果这是一个单节点的Eureka Server
#    #不需要同步其他节点的数据，设置为false
#    fetch-registry: false
#    #是否将自己注册到Eureka Server,默认是 true,由于当前应用时单节点的Eureka Server
#    #需要设置为false
#    register-with-eureka: false
#    #设置Eureka Server 所在的地址，查询服务和注册服务都要依赖这个地址
#    service-url:
#      defaltZone: htttp://${spring.application.name}:${server.port}/eureka/